[versions]
agp = "8.7.3"
gms = "4.4.2"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
protobuf = "0.9.4"
versions = "0.51.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# https://developers.google.com/android/guides/google-services-plugin
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }

# https://github.com/google/protobuf-gradle-plugin
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }

# https://github.com/ben-manes/gradle-versions-plugin
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }