name: Alpha Build

on:
  workflow_dispatch:

jobs:
  build-alpha:
    name: Build Alpha Apk
    runs-on: macos-latest
    if: github.repository == 'okami-horo/BVG'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          submodules: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit

      - name: Write google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add jks file
        run: |
          echo "${{ secrets.SIGN_KEY }}" | tr -d '\n\r\t ' | base64 -D > key.jks
          ls -la key.jks
          keytool -list -v -keystore key.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}" || true

      - name: Build apk
        run: |
          ./gradlew assembleDefaultAlpha assembleDefaultDebug \
            -Pkeystore.path=key.jks \
            -Pkeystore.pwd=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pkeystore.alias=${{ secrets.KEY_ALIAS }} \
            -Pkeystore.alias_pwd=${{ secrets.KEY_ALIAS_PASSWORD }}

      - name: Read alpha apk output metadata
        id: apk-meta-alpha
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/default/alpha/output-metadata.json

      - name: Read alpha debug apk output metadata
        id: apk-meta-alpha-debug
        uses: juliangruber/read-file-action@v1
        with:
          path: app/build/outputs/apk/default/debug/output-metadata.json

      - name: Parse apk infos
        id: apk-infos
        run: |
          echo "alpha_info_version_code=${{ fromJson(steps.apk-meta-alpha.outputs.content).elements[0].versionCode }}" >> $GITHUB_ENV
          echo "alpha_info_version_name=${{ fromJson(steps.apk-meta-alpha.outputs.content).elements[0].versionName }}" >> $GITHUB_ENV
          echo "alpha_debug_info_version_code=${{ fromJson(steps.apk-meta-alpha-debug.outputs.content).elements[0].versionCode }}" >> $GITHUB_ENV
          echo "alpha_debug_info_version_name=${{ fromJson(steps.apk-meta-alpha-debug.outputs.content).elements[0].versionName }}" >> $GITHUB_ENV

      - name: Generate release info
        run: |
          echo "tag_name=alpha-${{ env.alpha_info_version_name }}-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          echo "changelog=Alpha build ${{ env.alpha_info_version_name }} (Build ${{ env.alpha_info_version_code }})" >> $GITHUB_ENV

      # upload artifacts alpha debug

      - name: Archive alpha debug build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Alpha debug build artifact
          path: app/build/outputs/apk/default/debug/BV_${{ env.alpha_debug_info_version_code }}_${{ env.alpha_debug_info_version_name }}_default_universal.apk

      # upload artifacts alpha

      - name: Archive default alpha build mappings
        uses: actions/upload-artifact@v4
        with:
          name: Alpha build mappings
          path: app/build/outputs/mapping/defaultAlpha

      - name: Archive alpha build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Alpha build artifact
          path: app/build/outputs/apk/default/alpha/BV_${{ env.alpha_info_version_code }}_${{ env.alpha_info_version_name }}_default_universal.apk

      # zip mapping because softprops/action-gh-release can't upload folder

      - name: Zip mapping
        run: zip -rj mapping.zip app/build/outputs/mapping/defaultAlpha

      # upload to github release

      - name: Publish Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/default/debug/BV_${{ env.alpha_debug_info_version_code }}_${{ env.alpha_debug_info_version_name }}_default_universal.apk
            app/build/outputs/apk/default/alpha/BV_${{ env.alpha_info_version_code }}_${{ env.alpha_info_version_name }}_default_universal.apk
            mapping.zip
          tag_name: ${{ env.tag_name }}
          name: ${{ env.alpha_info_version_name }}
          prerelease: true
          body: ${{ env.changelog }}
          target_commitish: ${{ github.sha }}